# Database
MYSQL_USERNAME: root
MYSQL_PASSWORD:
MYSQL_HOST:
MYSQL_PORT: 3306
MYSQL_DATABASE: spring_customer

# Server Config
CONTAINER_PORT: 8080
ACTIVE_PROFILE: dev

# Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: ${EMAIL_USERNAME}
EMAIL_PASSWORD: ${EMAIL_PASSWORD}
VERIFY_EMAIL_HOST: http://localhost:${CONTAINER_PORT}

UI_APP_URL: http://localhost:4200

JWT_SECRET: testsecret